<?php
// Enhanced Help mod
// Main stuff
$txt['ln_main_title'] = 'LearnNavi Community - obecná nápověda a informace';
$txt['ln_bbc_help'] = 'Nápověda pro Bulletin Board kódy (BBC)';
$txt['ln_bbc_main'] = 'Bulletin Board kódy (též BBCodes) jsou způsob, jak formátovat příspěvky v SMF a na mnoha jiných online fórech. Některá fóra mají speciální BB kódy s různými modifikacemi pro své potřeby. Protože tyto kódy jsou upravené, nejsou popsány v oficiální nápovědě nebo SMF online manuálu.';
$txt['ln_bbc_main2'] = 'Zde najdete všechny BB kódy, které lze používat na fóru LearnNavi.org:';
$txt['ln_bbc_syn'] = 'Syntax';
$txt['ln_bbc_exa'] = 'Příklad';
$txt['ln_bbc_out'] = 'Výsledek';
$txt['ln_bbc_tex'] = 'Text';
$txt['ln_bbc_opt'] = 'Parametr';
$txt['ln_bbc_lin'] = 'Odkaz';
$txt['ln_group_page'] = 'Užitečné odkazy: <a id="button_rss" class="new_win" href="http://forum.learnnavi.org/index.php?topic=6770.0">Pravidla a politiky</a> | <a id="button_rss" class="new_win" href="http://forum.learnnavi.org/index.php?action=groups">Seznam skupin</a>';
// General help
$txt['ln_main_text1'] = '<strong>Přihlášení</strong><br />Pro úspěšné přihlášení musíte použít vaše <strong>přihlašovací jméno</strong> (nepleťte si je s vaším <strong>zobrazovaným jménem</strong>!). Přihlašovací jméno je jméno, které jste použili při registraci vašeho účtu na tomto fóru a používá se pro přihlášení do SMF fóra.';
$txt['ln_main_text2'] = '<strong>Bezpečnost účtu</strong><br />Na svůj účet byste si měli dávat pozor, zejména co se jeho ochrany týče. Pokud odcházíte od počítače, použijte tlačítko Odhlásit, abyste zabránili krádeži nebo zneužití účtu.';
// Examples
$txt['ln_bbc_b'] = 'Tento text je tučný.';
$txt['ln_bbc_i'] = 'Tento text je kurzíva.';
$txt['ln_bbc_u'] = 'Tento text je podtržený.';
$txt['ln_bbc_s'] = 'Tento text je přeškrtnutý.';
$txt['ln_bbc_ean'] = 'Tento text je modrý.';
$txt['ln_bbc_big'] = 'Tento text se zvětší.';
$txt['ln_bbc_font'] = 'Tento text používá font Courier';
$txt['ln_bbc_font_info'] = 'Zobrazeny budou pouze fonty nainstalované na počítači uživatele, proto je používejte s rozmyslem!';
$txt['ln_bbc_left'] = 'Tento text je na levé straně.';
$txt['ln_bbc_center'] = 'Tento text je vystředěn.';
$txt['ln_bbc_right'] = 'Tento text je napravé straně.';
$txt['ln_bbc_ln_link'] = 'http://learnnavi.org/';
$txt['ln_bbc_ln_text'] = 'LearnNavi.org';
$txt['ln_bbc_iurl'] = 'Tag iurl obvykle odkazuje na pojmenované místo dokumentu (kotva, anchor) nebo určité ID (jako je ID příspěvku) v tomtéž okně nebo záložce web prohlížeče. Tento tag může být použit jako odkaz na jiné stránky - stejně jako běžný tag url - avšak neotevře nové okno / záložku prohlížeče. Tag je velmi užitečný pro rozsáhlé příspěvky, které mají obsah (table of content).';
$txt['ln_bbc_lin2'] = 'Odkaz, #anchor nebo #ID';
$txt['ln_bbc_anchor'] = 'Unikátní jméno, nebo kombinace písmen a číslic, ale ne pouze číslice.';
$txt['ln_bbc_anchor2'] = 'Text nebo ponechte prázdné';
$txt['ln_bbc_email'] = 'Mailová adresa';
$txt['ln_bbc_email_text'] = 'Napiš mi zprávu.';
$txt['ln_bbc_table1'] = 'definuje tabulku';
$txt['ln_bbc_table2'] = 'definuje řádek';
$txt['ln_bbc_table3'] = 'definuje buňku';
$txt['ln_bbc_table4'] = 'Je nutné použít všechny tabulkové tagy společně, jak ukazuje příklad:';
$txt['ln_bbc_spoiler'] = 'Tento text je skrytý.';
$txt['ln_bbc_desc'] = 'Text nebo překlad.';
$txt['ln_bbc_desc1'] = 'Kaltxì!';
$txt['ln_bbc_desc2'] = 'Ahoj!';
$txt['ln_bbc_col_spec'] = 'Existují také čtyři speciální tagy pro barvy:';
$txt['ln_bbc_trans'] = 'Tento text by měl být transparentní.';
$txt['ln_bbc_li_1'] = 'Element "list" může mít následující volby jako parametr: ';
$txt['ln_bbc_li_2'] = 'Následující volby mohou být použity náhradou za první "li" elementu: ';
$txt['ln_bbc_img'] = 'Odkaz na obrázek';
$txt['ln_bbc_img_opt'] = 'Tag img může mít až tři nepovinné parametry. X a Y jsou číslo, "alt" obsahuje text, který se zobrazí v případě, že obrázek není možné načíst.';
$txt['ln_bbc_sup'] = 'Tento text je horní index';
$txt['ln_bbc_sub'] = 'Tento text je dolní index';
$txt['ln_bbc_glow'] = 'Tři parametry (např. red, 2, 300) v tagu glow jsou barva, síla a šířka.';
$txt['ln_bbc_shadow'] = 'Dva parametry (např. red, left) v tagu shadow jsou barva a směr.';
$txt['ln_bbc_rtl1'] = 'Zprava-do-Leva!';
$txt['ln_bbc_ltr2'] = 'Zleva-do-Prava!';
$txt['ln_bbc_rtl'] = 'Typické použití je vypsání textu v arabštině nebo hebrejštině na anglickém fóru.';
$txt['ln_bbc_ltr'] = 'Typické použití je vypsání textu v angličtině na arabském nebo hebrejském fóru.';
$txt['ln_bbc_ac_ab'] = 'Zobrazí plný význam zkratky nebo akronymu po najetí myší.';
$txt['ln_bbc_abb'] = 'Zkratka';
$txt['ln_bbc_acr'] = 'Akronym';
$txt['ln_bbc_qauth'] = 'Autor';
$txt['ln_bbc_qtext'] = 'Citovaný příspěvek';
$txt['ln_bbc_audio'] = 'Odkaz na audio soubor typu .mp3, .ogg nebo .wav';
$txt['ln_bbc_nobbc'] = 'Všechny BB kódy a odkazy budou uvnitř tohoto tagu zakázány.';
$txt['ln_bbc_time'] = 'Konvertovat časovou značku v Unix formátu na čas čitelný člověkem';
// Titles
$txt['ln_bbc_1'] = 'Tučně / Kurzíva / Podtržení / Přeškrtnutí';
$txt['ln_bbc_2'] = 'Barvy';
$txt['ln_bbc_3'] = 'Velikost fontu';
$txt['ln_bbc_4'] = 'Typ fontu';
$txt['ln_bbc_5'] = 'Vlevo / Vystředit / Vpravo';
$txt['ln_bbc_6'] = 'Odkazy and kotvy';
$txt['ln_bbc_7'] = 'Email';
$txt['ln_bbc_8'] = 'Tabulky';
$txt['ln_bbc_9'] = 'Spoiler';
$txt['ln_bbc_10'] = 'Popis';
$txt['ln_bbc_11'] = 'Seznam';
$txt['ln_bbc_12'] = 'Vložené obrázky';
$txt['ln_bbc_13'] = 'Citace';
$txt['ln_bbc_14'] = 'Kód';
$txt['ln_bbc_15'] = 'PHP kód';
$txt['ln_bbc_16'] = 'Horní a dolní indexy';
$txt['ln_bbc_17'] = 'Žár and stín';
$txt['ln_bbc_18'] = 'Zprava-do-Leva and Zleva-do-Prava';
$txt['ln_bbc_19'] = 'Zkratky a Akronymy';
$txt['ln_bbc_20'] = 'Další BB kódy (pouze syntax)';
// end of Enhanced Help mod
?>
