<?php
// Enhanced Help mod
// Main stuff
$txt['ln_main_title'] = 'LearnNavi Community General Help and Info';
$txt['ln_bbc_help'] = 'Bulletin Board Code (BBC) Help';
$txt['ln_bbc_main'] = 'Bulletin Board Codes or BBCodes are a way to format posts in SMF and in many other places online. Some forums have special BB codes by various modifications for their need. As those codes are custom, they are not available in the official help page or SMF Online Manual.';
$txt['ln_bbc_main2'] = 'Here you can find all BBCodes you can use on LearnNavi.org forum:';
$txt['ln_bbc_syn'] = 'Syntax';
$txt['ln_bbc_exa'] = 'Example';
$txt['ln_bbc_out'] = 'Result';
$txt['ln_bbc_tex'] = 'Text';
$txt['ln_bbc_opt'] = 'Option';
$txt['ln_bbc_lin'] = 'Link';
$txt['ln_group_page'] = 'Useful links: <a id="button_rss" class="new_win" href="http://forum.learnnavi.org/index.php?topic=6770.0">Site Rules</a> | <a id="button_rss" class="new_win" href="http://forum.learnnavi.org/index.php?action=groups">Group Page</a>';
// General help
$txt['ln_main_text1'] = '<strong>Login</strong><br />To login successfully, you have to use your <strong>username</strong> (not to be confused with your <strong>display name</strong>!). A username is the name used to login to an SMF forum and it is the name you have used for register an account on this forum.';
$txt['ln_main_text2'] = '<strong>Account Security</strong><br />You should pay attention to your forum account, particulary its protection. Use the logout button if you have to go or not at your computer to prevent account theft.';
// Examples
$txt['ln_bbc_b'] = 'This text is bold.';
$txt['ln_bbc_i'] = 'This text is italic.';
$txt['ln_bbc_u'] = 'This text is underlined.';
$txt['ln_bbc_s'] = 'This text is struck through.';
$txt['ln_bbc_ean'] = 'This text is blue.';
$txt['ln_bbc_big'] = 'This text becommes big.';
$txt['ln_bbc_font'] = 'This text uses the Courier font';
$txt['ln_bbc_font_info'] = 'Only fonts installed on the user\'s computer will be displayed, so use with caution!';
$txt['ln_bbc_left'] = 'This text is on the left side.';
$txt['ln_bbc_center'] = 'This text is centered.';
$txt['ln_bbc_right'] = 'This text is on right side';
$txt['ln_bbc_ln_link'] = 'http://learnnavi.org/';
$txt['ln_bbc_ln_text'] = 'LearnNavi.org';
$txt['ln_bbc_iurl'] = 'The iurl tag usually links to an anchor or certain IDs (like post ID) on the same windows or browser tab. This tag can be used to link to other pages - like a normal url - but it does not open a new windows or browser tab. This tag is very useful for large posts that have a table of content.';
$txt['ln_bbc_lin2'] = 'Link, #anchor name or #ID';
$txt['ln_bbc_anchor'] = 'A unique name, or letter-number combination, but not only numbers.';
$txt['ln_bbc_anchor2'] = 'Text or let it empty';
$txt['ln_bbc_email'] = 'Email';
$txt['ln_bbc_email_text'] = 'Write me an email.';
$txt['ln_bbc_table1'] = 'defines a table';
$txt['ln_bbc_table2'] = 'defines a rows';
$txt['ln_bbc_table3'] = 'defines a cell';
$txt['ln_bbc_table4'] = 'One have to use all table tags together as following example:';
$txt['ln_bbc_spoiler'] = 'This text is hidden.';
$txt['ln_bbc_desc'] = 'Text or translation.';
$txt['ln_bbc_desc1'] = 'Kaltxì!';
$txt['ln_bbc_desc2'] = 'Hello!';
$txt['ln_bbc_col_spec'] = 'There are also four special color tags:';
$txt['ln_bbc_trans'] = 'This text should be transparent.';
$txt['ln_bbc_li_1'] = 'The "list" element can have following as option: ';
$txt['ln_bbc_li_2'] = 'Following options can be used by replacing the first "li" element: ';
$txt['ln_bbc_img'] = 'Link to image';
$txt['ln_bbc_img_opt'] = 'The img tag can have up to three optional attributes. X and Y should be a number while "alt" can have a text that will be visible in case if the image could not be loaded.';
$txt['ln_bbc_sup'] = 'This text is high';
$txt['ln_bbc_sub'] = 'This text is low';
$txt['ln_bbc_glow'] = 'The three attributes (eg. red, 2, 50) in the glow tag are color, strength and width.';
$txt['ln_bbc_shadow'] = 'The two attributes (eg. red, left) in the shadow tag are color and direction.';
$txt['ln_bbc_rtl1'] = 'Right-to-Left!';
$txt['ln_bbc_ltr2'] = 'Left-to-Right!';
$txt['ln_bbc_rtl'] = 'Typical usage would be to post Arabic or Hebrew in an English forum.';
$txt['ln_bbc_ltr'] = 'Typical usage would be to post English in an Arabic or Hebrew forum.';
$txt['ln_bbc_ac_ab'] = 'Displays the full expression for the abbreviation or acronym on mouseover.';
$txt['ln_bbc_abb'] = 'Abbreviation';
$txt['ln_bbc_acr'] = 'Acronym';
$txt['ln_bbc_qauth'] = 'Author';
$txt['ln_bbc_qtext'] = 'Quoted post';
$txt['ln_bbc_audio'] = 'Link to an audio file that should be a .mp3, .ogg or .wav file';
$txt['ln_bbc_nobbc'] = 'All BB codes and links will be disabled inside this tag.';
$txt['ln_bbc_time'] = 'Convert a Unix Timestamp into a time recognizable by people';
// Titles
$txt['ln_bbc_1'] = 'Bold / Italic / Underline / Strikethrough';
$txt['ln_bbc_2'] = 'Color';
$txt['ln_bbc_3'] = 'Font size';
$txt['ln_bbc_4'] = 'Font face';
$txt['ln_bbc_5'] = 'Left / Center / Right';
$txt['ln_bbc_6'] = 'Hyperlink and Anchor';
$txt['ln_bbc_7'] = 'Email';
$txt['ln_bbc_8'] = 'Table';
$txt['ln_bbc_9'] = 'Spoiler';
$txt['ln_bbc_10'] = 'Description';
$txt['ln_bbc_11'] = 'List';
$txt['ln_bbc_12'] = 'Embed images';
$txt['ln_bbc_13'] = 'Quote';
$txt['ln_bbc_14'] = 'Code';
$txt['ln_bbc_15'] = 'PHP Code';
$txt['ln_bbc_16'] = 'Superscript and Subscript';
$txt['ln_bbc_17'] = 'Glow and Shadow';
$txt['ln_bbc_18'] = 'Right-to-Left and Left-to-Right';
$txt['ln_bbc_19'] = 'Abbreviation and Acronym';
$txt['ln_bbc_20'] = 'More BB Codes (Syntax only)';
// end of Enhanced Help mod
?>
